
server:
  port: 10001

dubbo:
  application:
    name: gmall-sso-server
  registry:
    address: zookeeper://129.211.77.216:2181
  consumer:
    check: false
    timeout: 10000


spring:
  redis:
    host: 129.211.77.216
